services:
  webterminal:
    build: ./webapp/server
    container_name: webterminal
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /:/host
    environment:
      - TZ=UTC
    depends_on:
      - ttyd

  ttyd:
    build: ./webterminal
    container_name: ttyd
    restart: unless-stopped
    ports:
      - "7681:7681"
