services:
  webapp:
    build: ./webapp/server
    container_name: webapp
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /:/host
      - user-data:/home/users
    environment:
      - TZ=UTC
      - FILE_EXPLORER_HOME=/home/webterm
      - TERMINAL_BASE_PORT=9000
      - TERMINAL_MAX_PORTS=500
    env_file:
      - .env

volumes:
  user-data:
