services:
  webterminal:
    build: ./webapp/server
    container_name: webterminal
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /:/host
      - webterminal-home:/home/webterm
    environment:
      - TZ=UTC
      - FILE_EXPLORER_HOME=/home/webterm
    depends_on:
      - ttyd

  ttyd:
    build: ./webterminal
    container_name: ttyd
    restart: unless-stopped
    ports:
      - "7681:7681"
    volumes:
      - webterminal-home:/home/webterm

volumes:
  webterminal-home:
